### PR TITLE
Major refactor

### PR DESCRIPTION
**Pull request by VanTudor**
alo @quest-bot-local loot #3

### CODE REVIEW

**Review by DefinitelyNotVanTudor — COMMENTED** [review]
a

**Review by DefinitelyNotVanTudor — APPROVED** [review]

**Review by DefinitelyNotVanTudor — APPROVED** [review]
good job. goo boi

**Review by DefinitelyNotVanTudor — APPROVED** [review]
good job boi

**Review by DefinitelyNotVanTudor — CHANGES_REQUESTED** [review]
bad boi

**Review by DefinitelyNotVanTudor — COMMENTED** [review]
niet

**Comment by VanTudor** [comment]
Hello world

**Pull request merged**
